version: "3"
services:
  mvtbenchdb:
    #build:
    #  context: ./data
    image: sourcepole/mvtbenchdb
    ports:
      - "127.0.0.1:5439:5432"

  t-rex:
    image: sourcepole/t-rex
    ports:
      - "127.0.0.1:6767:6767"
    volumes:
      - ./t-rex:/var/data/in:ro
      - ./tiles:/var/data/tiles
      - ./maps:/var/data/maps:ro

  mapserver:
    # https://github.com/camptocamp/docker-mapserver/tree/7.2
    image: camptocamp/mapserver:latest
    user: www-data
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./MapServer/ne.map:/etc/mapserver/mapserver.map:ro
      - ./MapServer/epsg:/usr/share/proj/epsg:ro

  mapcache:
    # https://github.com/camptocamp/docker-mapcache
    image: camptocamp/mapcache:latest
    user: www-data
    ports:
      - "127.0.0.1:6767:8080"
    volumes:
      - ./MapServer/mapcache_mvt.xml:/etc/mapcache/mapcache.xml:ro
      - ./tiles:/var/sig/tiles
